project:
  type: website

website:
  title: "Disentangling"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About this project
  

format:
  html:
    theme: lux
    css: styles.css
    toc: true

editor: visual

# I kind of like the lux theme: